### ISSUE TITLE
Require bearer tokens for "note" calls

### ISSUE THREAD

**Issue by zahradtj** [CSGY-9223-Group3/lab1#2]
GET/PUT/POST/DELETE calls to `/note/<id>` need to require a bearer token

**Comment by esamnyu** [comment]
This feature has been implemented. All GET/PUT/POST/DELETE calls to `/note/<id>` now require a bearer token for authentication. Here's a summary of the changes:

- Added a `@token_required` decorator that checks for a valid bearer token in the Authorization header.
- Applied this decorator to all note-related endpoints:
  - GET /notes/<note_id>
  - POST /notes/<note_id>
  - PUT /notes/<note_id>
  - DELETE /notes/<note_id>

The implementation can be found in the latest commit 97bb4b0e5bebdd604a0e951710c3eda723afcb96.

Please review and let me know if any further changes are needed.
