### ISSUE TITLE
Hardcoded Secret Key

### ISSUE THREAD

**Issue by dr3394** [CSGY-9223-Group3/lab1#7]
The `SECRET_KEY` is hardcoded in the code (`SECRET_KEY = "cf4d68b60166f3e77fa11213797e2ee9ace4e813eead3fdbc522079ecee9beb2"`), which poses a serious security risk. If the source code is publicly available, anyone can access this secret key and use it to generate or decode JWT tokens.

Store the `SECRET_KEY` as an environment variable.

**Comment by jjl9839** [comment]
Within GitHub, secret key is stored as an environment variable should we need to run the code in GitHub Actions.

**Comment by esamnyu** [comment]
This issue has been addressed in the latest commit. The SECRET_KEY is now retrieved from an environment variable, eliminating the security risk of a hardcoded key in the source code. The PR has been updated to reflect these changes. Unless there are any further concerns, this issue can be considered resolved.
